# 00. PyTorch Fundamentals

```
Date: 19 Dec. 2024
Course: PyTorch for Deep Learning
Creator: KeahiXie
```

In [ ]:
import torch
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
print(torch.__version__)

2.1.0+cu121


## Introduction Tensor

### Creating Tensor

In [ ]:
# Scalar

scalar = torch.tensor(8)
print(f"The tensor is {scalar} and the dimension is {scalar.ndim}")

The tensor is 8 and the dimension is 0


In [ ]:
# Get the tensor back as python int

scalar.item()

8

In [ ]:
#Vector

vector = torch.tensor([8,8])
print(f"The tensor is {vector} and the dimension is {vector.ndim}, also we have to know the shape is {vector.shape}")

The tensor is tensor([8, 8]) and the dimension is 1, also we have to know the shape is torch.Size([2])


In [ ]:
#Matrix
matrix = torch.tensor([[7,7],
                       [8,8]])
print(f"The tensor is {matrix} and the dimension is {matrix.ndim}, also we have to know the shape is {matrix.shape}")

The tensor is tensor([[7, 7],
        [8, 8]]) and the dimension is 2, also we have to know the shape is torch.Size([2, 2])


In [ ]:
#Tensor
tensor = torch.tensor([
    [[1,2,3],
     [3,6,9],
     [2,4,5]],
    [[2,5,7],
     [9,6,3],
     [6,9,3]]
])
print(f"The tensor is {tensor} and the dimension is {tensor.ndim}, also we have to know the shape is {tensor.shape}")

The tensor is tensor([[[1, 2, 3],
         [3, 6, 9],
         [2, 4, 5]],

        [[2, 5, 7],
         [9, 6, 3],
         [6, 9, 3]]]) and the dimension is 3, also we have to know the shape is torch.Size([2, 3, 3])


In [ ]:
tensor[0][0][0]

tensor(1)

In [ ]:
print(f"{tensor[0]}, \n {tensor[0][0]},  \n{tensor[0][0][0]}")

tensor([[1, 2, 3],
        [3, 6, 9],
        [2, 4, 5]]), 
 tensor([1, 2, 3]),  
1


Note: You might've noticed me using ***lowercase*** letters for scalar and vector and ***uppercase*** letters for MATRIX and TENSOR. This was on purpose. In practice, you'll often see scalars and vectors denoted as lowercase letters such as y or a. And matrices and tensors denoted as uppercase letters such as X or W.

### Random tensors

Why random tensors?

`Start with random numbers -> look at data -> update random numbers -> look at data -> updata random numbers`



NOTE: you can be ignore the argument **size** in the `torch.rand`

In [ ]:
#Create a random tensors of shape(size) with (3,4)
random_tensor = torch.rand(3,4,5)
random_tensor

tensor([[[0.7442, 0.2057, 0.4930, 0.2117, 0.7755],
         [0.8215, 0.7662, 0.4412, 0.1801, 0.2043],
         [0.4422, 0.4840, 0.8884, 0.3215, 0.3718],
         [0.6293, 0.7242, 0.5167, 0.1668, 0.0086]],

        [[0.2973, 0.9419, 0.3970, 0.3256, 0.0857],
         [0.1326, 0.2515, 0.7102, 0.4862, 0.6740],
         [0.1093, 0.9357, 0.3284, 0.8213, 0.0794],
         [0.6808, 0.0788, 0.5988, 0.7655, 0.8102]],

        [[0.6421, 0.6408, 0.1608, 0.2318, 0.5446],
         [0.3180, 0.9428, 0.5637, 0.5231, 0.0546],
         [0.2852, 0.3453, 0.2161, 0.0272, 0.2851],
         [0.9290, 0.0206, 0.2455, 0.5220, 0.2814]]])

In [ ]:
#Create a random tensor with similar shape to an image tensor
random_image_size_tensor = torch.rand(size = (224, 224, 3)) #high, width, colour channel

### Zeros and ones

NOTE:
1. These are two way to create a tensor of all zeros
2. Why should we create the zeros: we should adjust the noisy of data, which is tell the model where you shold ignore.
3. The most common data type of tensor is `float32`

In [ ]:
# Way 1: Create a tensor of all zeros
zeros = torch.zeros(size = (3, 4))
zeros

tensor([[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]])

In [ ]:
# Way 2: Create a tensor of all zeros
random_tensor = torch.rand(3,4)
zeros * random_tensor

tensor([[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]])

In [ ]:
#Create a tensor of all ones
ones = torch.ones(size = (3,4))
ones

tensor([[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]])

In [ ]:
ones.dtype

torch.float32

### Creating a range of tensors and tensors-like

In [ ]:
#Use torch.range() and get deprecated message, use torch.arange()
one_to_ten = torch.arange(start = 1, end = 11, step =1)
one_to_ten

tensor([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [ ]:
 #Creating tensor like
 ten_zeros = torch.zeros_like(one_to_ten)
 ten_zeros

tensor([0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

### Tensor datatypes


**Note**: Tensor datatypes is one of the 3 big errors you'll run into with PyTorch & Deep Learning:
1. Tensors not right datatype
2. Tensors not right shape
3. Tensors not on the right device

In [ ]:
#Float 32 tensor
float_32_tensor = torch.tensor([3.0, 6.0, 9.0],
                               dtype = None, # what data type you wanna use(eg. float 32 and float 16)
                               device = None,
                               requires_grad= False)
float_32_tensor

tensor([3., 6., 9.])

In [ ]:
float_32_tensor.dtype

torch.float32

In [ ]:
float_16_tensor = float_32_tensor.type(torch.float16)
float_16_tensor

tensor([3., 6., 9.], dtype=torch.float16)

In [ ]:
int_32_tensor = torch.tensor([3, 6, 9], dtype = torch.long)
int_32_tensor

tensor([3, 6, 9])

### Get information from tensors(by attribute)
1. Tensors not right datatype - to do get datatype from a tensor, can use `tensor.dtype`
2. Tensors not right shape - to get shape from a tensor, can use `tensor.shape`
3. Tensors not on the right device - to get device from a tensor, can use `tensor.device`

In [ ]:
#Create a tensor
some_tensor = torch.rand(3,4)
some_tensor

tensor([[0.8617, 0.6551, 0.6463, 0.9223],
        [0.2555, 0.6942, 0.0356, 0.9885],
        [0.2059, 0.9573, 0.5210, 0.9532]])

In [ ]:
#Find out details about some tensor
print(some_tensor)
print(f"Datatype of tensor:{some_tensor.dtype}")
print(f"Shape of tensor:{some_tensor.shape}")
print(f"Device of tensor:{some_tensor.device}")

tensor([[0.8617, 0.6551, 0.6463, 0.9223],
        [0.2555, 0.6942, 0.0356, 0.9885],
        [0.2059, 0.9573, 0.5210, 0.9532]])
Datatype of tensor:torch.float32
Shape of tensor:torch.Size([3, 4])
Device of tensor:cpu



### Manipulating Tensors(tensor operations)
Tensor operations include(all operation is not inplace):
* Adddition
* Subtraction
* Multiplication
* Division
* **Matrix multiplication**


In [ ]:
#Create a tensor and add 777 to it
tensor = torch.tensor([1,2,3])
tensor + 777

tensor([778, 779, 780])

In [ ]:
tensor.add(10) # different way to achieve

tensor([11, 12, 13])

In [ ]:
tensor * 10

tensor([10, 20, 30])

In [ ]:
tensor

tensor([1, 2, 3])

### Matrix multiplication

Two main ways of performing multiplication in nerual networks and deep learning
1. Element-wise multiplication
2. Matrix multiplication(dot product)

There are two main rule that performing matrix multiplication needs to satisfy:
1. The **inner dimensions** must match:
* `(3, 2) @ (3, 2)` won't work
* `(2, 3) @ (3, 2)` will work
* `(3, 2) @ (2, 3)` will work
2. the resulting matrix has the shape of the outer dimensions:
* `(2, 3) @ (3, 2)` -> `(2, 2)`
* `(3, 2) @ (2, 3)` -> `(3, 3)`



In [ ]:
# Element wise multiplication
print(tensor, "*", tensor)
print(f"Euqual:{ tensor * tensor}")

tensor([1, 2, 3]) * tensor([1, 2, 3])
Euqual:tensor([1, 4, 9])


In [ ]:
#Matrix multiplication
torch.matmul(tensor, tensor)

tensor(14)

In [ ]:
#Matrix multiplication
1 * 1 + 2 * 2 + 3 * 3

14

### one of the most common errors in deep learning: shape errors


In [ ]:
#Shape for matrix multiplication
tensor_A = torch.rand(size = (3,2))
tensor_B = torch.rand(size = (3,2))

In [ ]:
#Let's take a trying to matrix multiplication directly
tensor_mm = tensor_A @ tensor_B # here, @ is the same as `torch.matmul()` and 'torch.mm()'(two different alias for matrix multiplication)


RuntimeError: ignored

In [ ]:
#here, the error is from the  different shape of our tensor
# the most common method is using 'tensor.transpose()' function(also have a alias with `T`)
print(f"we get a new matrix after using `tensor.T` function that is\n\n {tensor_B.T} \n")
print(f"the shape of the new tensor is{tensor_B.T.shape}")

we get a new matrix after using `tensor.T` function that is

 tensor([[0.8249, 0.4652, 0.3365],
        [0.7237, 0.6622, 0.5331]]) 

the shape of the new tensor istorch.Size([2, 3])


In [ ]:
# using tensor.mm() function again
tensor_after_T = tensor_A @ tensor_B.T

### Finding the min, max, mean, sum, etc(tensor aggregation)


In [ ]:
#Create a tensor
x = torch.arange(1, 100, 10)
x

tensor([ 1, 11, 21, 31, 41, 51, 61, 71, 81, 91])

In [ ]:
# Find the min
torch.min(x)
x.min()

tensor(1)

In [ ]:
# Find the max
torch.max(x)
x.max()

tensor(91)

In [ ]:
#Find the mean - note: the torch.mean() function requires a tensor of float32 datatype to work
torch.mean(x.type(torch.float32))
x.type(torch.float32).mean()

tensor(46.)

In [ ]:
x.sum()

tensor(460)

###Finding the positional min and max
1. To find the position in tensor that has minimum value with `argmin()`
1. To find the position in tensor that has maxmum value with `argmax()`
**Note**: The value returned is index position of target tensor where the minimum value occurs

In [ ]:
# Find the minimum
x.argmin()

tensor(0)

In [ ]:
tensor[0]

tensor(1)

## Reshaping, stacking, squeezing, and unsqueezing tensors
* Reshaping - reshape an input tensor to a defined shape
* View - Renturn a view of an input tensor of certain shape but keep the same memory as the original tensor
* Stacking - combine multiple tensors on top of each other(vstack) or side by side(hstack)
* Squeeze - removes all `1` dimensions from a tensor
* Unsqueeze - add a `1` dimensions to a target tensor
* Permute - Return a ***view*** of the input with dimensions permuted(swapped) in a certain way
 * **Note** : Please take a look the the returns after you used .permute(), that is a **VIEW**

In [ ]:
import torch
x = torch.arange(1., 10)
x.shape

torch.Size([9])

In [ ]:
# Add an extra dimension
x_reshaped = x.reshape(1,9)
x_reshaped.shape

torch.Size([1, 9])

In [ ]:
# Change the view
z = x.view(3, 3)
z, z.shape

(tensor([[5., 2., 3.],
         [4., 5., 6.],
         [7., 8., 9.]]),
 torch.Size([3, 3]))

In [ ]:
# changing z changes x(because a view of a tensor shares the memory as original intput)
z[:,0] = 5
z,x

(tensor([[5., 2., 3.],
         [5., 5., 6.],
         [5., 8., 9.]]),
 tensor([5., 2., 3., 5., 5., 6., 5., 8., 9.]))

In [ ]:
# stack tensors on top of each oher
x_stacked = torch.stack([z,z,z,z],dim= 0)
x_stacked, x_stacked.shape

(tensor([[[5., 2., 3.],
          [5., 5., 6.],
          [5., 8., 9.]],
 
         [[5., 2., 3.],
          [5., 5., 6.],
          [5., 8., 9.]],
 
         [[5., 2., 3.],
          [5., 5., 6.],
          [5., 8., 9.]],
 
         [[5., 2., 3.],
          [5., 5., 6.],
          [5., 8., 9.]]]),
 torch.Size([4, 3, 3]))

In [ ]:
x_stacked = torch.stack([z,z,z,z],dim= 1)
x_stacked, x_stacked.shape

(tensor([[[5., 2., 3.],
          [5., 2., 3.],
          [5., 2., 3.],
          [5., 2., 3.]],
 
         [[5., 5., 6.],
          [5., 5., 6.],
          [5., 5., 6.],
          [5., 5., 6.]],
 
         [[5., 8., 9.],
          [5., 8., 9.],
          [5., 8., 9.],
          [5., 8., 9.]]]),
 torch.Size([3, 4, 3]))

In [ ]:
x_stacked = torch.stack([z,z,z,z],dim= 2)
x_stacked, x_stacked.shape

(tensor([[[5., 5., 5., 5.],
          [2., 2., 2., 2.],
          [3., 3., 3., 3.]],
 
         [[5., 5., 5., 5.],
          [5., 5., 5., 5.],
          [6., 6., 6., 6.]],
 
         [[5., 5., 5., 5.],
          [8., 8., 8., 8.],
          [9., 9., 9., 9.]]]),
 torch.Size([3, 3, 4]))

In [ ]:
#torch.squeeze() - removes all single dimension from a target tensor
print(f"Previous tensor: {x_reshaped}")
print(f"Previous shape: {x_reshaped.shape}")


#Remove extra dimensions from x_reshaped
x_squeezed = x_reshaped.squeeze()
print(f"\nNew tensor: {x_squeezed}")
print(f"\nNew tensor shape: {x_squeezed.shape}")


Previous tensor: tensor([[5., 2., 3., 5., 5., 6., 5., 8., 9.]])
Previous shape: torch.Size([1, 9])

New tensor: tensor([5., 2., 3., 5., 5., 6., 5., 8., 9.])

New tensor shape: torch.Size([9])


In [ ]:
#torch.unsqueeze() - add a single dimension to a target tensor at a specific dimension
print(f"\nPrevious tensor: {x_squeezed}")
print(f"\nPrevious shape: {x_squeezed.shape}")

#Add an extra dimension with unsqueeze
x_unsqueezed = x_squeezed.unsqueeze(dim = 0)
print(f"\nNew tensor:{x_unsqueezed}")
print(f"\nNew shape: {x_unsqueezed.shape}")

x_unsqueezed = x_squeezed.unsqueeze(dim = 1)
print(f"\nNew tensor:{x_unsqueezed}")
print(f"\nNew shape: {x_unsqueezed.shape}")



Previous tensor: tensor([5., 2., 3., 5., 5., 6., 5., 8., 9.])

Previous shape: torch.Size([9])

New tensor:tensor([[5., 2., 3., 5., 5., 6., 5., 8., 9.]])

New shape: torch.Size([1, 9])

New tensor:tensor([[5.],
        [2.],
        [3.],
        [5.],
        [5.],
        [6.],
        [5.],
        [8.],
        [9.]])

New shape: torch.Size([9, 1])


In [ ]:
#torch.permute - rearranges the dimensions of a target tensor in a specified order
x_original = torch.rand(size = (224, 244, 3))

#Permute the original tensor to rearrange the axis(or dim) order
x_permuted = x_original.permute(2, 0, 1) # shift axis 0->1, 1->2, 2->0

print(f"Previous shape: {x_original.shape}")
print(f"New shape: {x_permuted.shape}")

Previous shape: torch.Size([224, 244, 3])
New shape: torch.Size([3, 224, 244])


In [ ]:
x_original

tensor([[[0.1738, 0.4938, 0.4063],
         [0.4484, 0.5490, 0.0318],
         [0.7489, 0.1275, 0.4013],
         ...,
         [0.2900, 0.2818, 0.7400],
         [0.3261, 0.7207, 0.5727],
         [0.1681, 0.5312, 0.4112]],

        [[0.7248, 0.0550, 0.0320],
         [0.2941, 0.8467, 0.2133],
         [0.2997, 0.1869, 0.2027],
         ...,
         [0.8458, 0.0615, 0.3186],
         [0.2939, 0.1868, 0.4969],
         [0.5471, 0.1619, 0.4484]],

        [[0.5916, 0.5047, 0.7754],
         [0.7760, 0.8779, 0.3271],
         [0.2841, 0.8544, 0.3097],
         ...,
         [0.6313, 0.0764, 0.5127],
         [0.6965, 0.0334, 0.1007],
         [0.0141, 0.5198, 0.3736]],

        ...,

        [[0.2300, 0.7517, 0.6178],
         [0.1968, 0.7516, 0.8427],
         [0.4127, 0.5862, 0.3119],
         ...,
         [0.4071, 0.7520, 0.7012],
         [0.3286, 0.8528, 0.7462],
         [0.3823, 0.8043, 0.5809]],

        [[0.2191, 0.1204, 0.0602],
         [0.7832, 0.3577, 0.4590],
         [0.

In [ ]:
x_original[0,0,0] = 3
x_original

tensor([[[3.0000, 0.4938, 0.4063],
         [0.4484, 0.5490, 0.0318],
         [0.7489, 0.1275, 0.4013],
         ...,
         [0.2900, 0.2818, 0.7400],
         [0.3261, 0.7207, 0.5727],
         [0.1681, 0.5312, 0.4112]],

        [[0.7248, 0.0550, 0.0320],
         [0.2941, 0.8467, 0.2133],
         [0.2997, 0.1869, 0.2027],
         ...,
         [0.8458, 0.0615, 0.3186],
         [0.2939, 0.1868, 0.4969],
         [0.5471, 0.1619, 0.4484]],

        [[0.5916, 0.5047, 0.7754],
         [0.7760, 0.8779, 0.3271],
         [0.2841, 0.8544, 0.3097],
         ...,
         [0.6313, 0.0764, 0.5127],
         [0.6965, 0.0334, 0.1007],
         [0.0141, 0.5198, 0.3736]],

        ...,

        [[0.2300, 0.7517, 0.6178],
         [0.1968, 0.7516, 0.8427],
         [0.4127, 0.5862, 0.3119],
         ...,
         [0.4071, 0.7520, 0.7012],
         [0.3286, 0.8528, 0.7462],
         [0.3823, 0.8043, 0.5809]],

        [[0.2191, 0.1204, 0.0602],
         [0.7832, 0.3577, 0.4590],
         [0.

In [ ]:
x_permuted

tensor([[[3.0000, 0.4484, 0.7489,  ..., 0.2900, 0.3261, 0.1681],
         [0.7248, 0.2941, 0.2997,  ..., 0.8458, 0.2939, 0.5471],
         [0.5916, 0.7760, 0.2841,  ..., 0.6313, 0.6965, 0.0141],
         ...,
         [0.2300, 0.1968, 0.4127,  ..., 0.4071, 0.3286, 0.3823],
         [0.2191, 0.7832, 0.3701,  ..., 0.1715, 0.6210, 0.6627],
         [0.1663, 0.6612, 0.4913,  ..., 0.4375, 0.0442, 0.5844]],

        [[0.4938, 0.5490, 0.1275,  ..., 0.2818, 0.7207, 0.5312],
         [0.0550, 0.8467, 0.1869,  ..., 0.0615, 0.1868, 0.1619],
         [0.5047, 0.8779, 0.8544,  ..., 0.0764, 0.0334, 0.5198],
         ...,
         [0.7517, 0.7516, 0.5862,  ..., 0.7520, 0.8528, 0.8043],
         [0.1204, 0.3577, 0.1004,  ..., 0.3344, 0.7376, 0.8140],
         [0.3594, 0.2418, 0.6624,  ..., 0.7920, 0.2136, 0.5927]],

        [[0.4063, 0.0318, 0.4013,  ..., 0.7400, 0.5727, 0.4112],
         [0.0320, 0.2133, 0.2027,  ..., 0.3186, 0.4969, 0.4484],
         [0.7754, 0.3271, 0.3097,  ..., 0.5127, 0.1007, 0.

## Indexing (selecting data from tensors)

Indexing with PyTorch is similar to indexing with Nunmpy

In [ ]:
#Create a tensor
import torch
x = torch.arange(1, 28).reshape(3, 3, 3)
x, x.shape

(tensor([[[ 1,  2,  3],
          [ 4,  5,  6],
          [ 7,  8,  9]],
 
         [[10, 11, 12],
          [13, 14, 15],
          [16, 17, 18]],
 
         [[19, 20, 21],
          [22, 23, 24],
          [25, 26, 27]]]),
 torch.Size([3, 3, 3]))

In [ ]:
#Let's index on our new tensor
x[0]


tensor([[1, 2, 3],
        [4, 5, 6],
        [7, 8, 9]])

In [ ]:
#Let's index on middle bracket(dim = 1)
x[0][0]


tensor([1, 2, 3])

In [ ]:
#Let's index on the most inner bracket(last diminsion)
x[0][2][2]

tensor(9)

In [ ]:
#YOu can also use ":" to select "all" of a target dimension
x[:,0]

tensor([[ 1,  2,  3],
        [10, 11, 12],
        [19, 20, 21]])

In [ ]:
#Get all values of the 0th dimenisions but  only index 2 of 2nd dimension
x[:,2]

tensor([[ 7,  8,  9],
        [16, 17, 18],
        [25, 26, 27]])

In [ ]:
#Get all values of the 0th dimension and 1st dimension but only index 2 of 2nd dimension
x[:,:,2]

tensor([[ 3,  6,  9],
        [12, 15, 18],
        [21, 24, 27]])

tensor([[ 3,  6,  9],
        [12, 15, 18],
        [21, 24, 27]])

In [ ]:
x[2,[0,1,2],[1,0,2]]

tensor([20, 22, 27])

## PyTorch tensors & NunPy
Numpy is a popular scientific Python numerical computing library
And becasue of this, PyTorch has functionality to interact with it

* Data in NumPy, want in PyTorch tensor -> `torch.from_numpy(ndarray)`
* PyTorch tensor , want in NumPy -> `torch.Tensor.numpy()`


In [ ]:
#NumPy array to tensor
import torch
import numpy as np

array  = np.arange(1.0, 8.0)
tensor = torch.from_numpy(array) #warning: when converting from numpy -> pytorch , PyTorch reflects numpy's default datatype of float64 unless specific otherwise
array, tensor

(array([1., 2., 3., 4., 5., 6., 7.]),
 tensor([1., 2., 3., 4., 5., 6., 7.], dtype=torch.float64))

In [ ]:
tensor.dtype

torch.float64

In [ ]:
tensor = tensor.type(torch.float32)
tensor.dtype

torch.float32

In [ ]:
# Change the value of array, what will this do to 'tensor'?
array = array + 1
array, tensor

(array([2., 3., 4., 5., 6., 7., 8.]), tensor([1., 2., 3., 4., 5., 6., 7.]))

In [ ]:
#Tensor to NUmpy array
tensor = torch.ones(7)
numpy_tensor = tensor.numpy()
tensor, numpy_tensor, tensor.dtype

(tensor([1., 1., 1., 1., 1., 1., 1.]),
 array([1., 1., 1., 1., 1., 1., 1.], dtype=float32),
 torch.float32)

##Reproducbility(trying to take random out of random)
In short, how a neural network learns:
`Start with random numbers -> tensor operations -> update random numbers to try and make them of the data -> again -> again -> again ...`
To reduce the randomness in neural network and PyTorch come the concept of **Random Seed**

Essentially what the random seed does is "flavor" the randomness


In [ ]:
import torch

#Create two random tensors
random_tensor_A = torch.rand(3, 4)
random_tensor_B = torch.rand(3, 4)

print(random_tensor_A)
print(random_tensor_B)
print(random_tensor_A == random_tensor_B)


tensor([[0.7082, 0.9728, 0.5566, 0.0669],
        [0.8468, 0.7694, 0.2961, 0.2109],
        [0.2666, 0.2105, 0.1191, 0.2181]])
tensor([[0.0892, 0.8930, 0.2591, 0.7212],
        [0.4107, 0.7851, 0.5301, 0.7730],
        [0.5722, 0.9534, 0.4399, 0.1723]])
tensor([[False, False, False, False],
        [False, False, False, False],
        [False, False, False, False]])


In [ ]:
#Let's make some random but reporducible tensors
#Set the random seed

RANDOM_SEED = 42
torch.manual_seed(RANDOM_SEED)
random_tensor_C = torch.rand(3, 4)
 #you have to reset RANDOM_SEED before youre using torch.rand() again
 #even you already used the torch.manual_seed()
torch.manual_seed(RANDOM_SEED)
random_tensor_D = torch.rand(3, 4)

print(random_tensor_C)
print(random_tensor_D)
print(random_tensor_C == random_tensor_D)

tensor([[0.8823, 0.9150, 0.3829, 0.9593],
        [0.3904, 0.6009, 0.2566, 0.7936],
        [0.9408, 0.1332, 0.9346, 0.5936]])
tensor([[0.8823, 0.9150, 0.3829, 0.9593],
        [0.3904, 0.6009, 0.2566, 0.7936],
        [0.9408, 0.1332, 0.9346, 0.5936]])
tensor([[True, True, True, True],
        [True, True, True, True],
        [True, True, True, True]])


##Running tensors and PyTorch objects on the GPUs(and making faster computations)
GPUs = faster computation on number , thanks to CUDA + NVIDIA hardware

### 1. Getting a GPU
1. Easiest - Use Google Colab for a free GPU (options to upgrade as well)
2. Use your own GPU - takes a little bit setup and requireds investment of purchasing a GPU
3. Use cloud computing - GCP, AWS


In [1]:
!nvidia-smi


Fri Dec 22 12:30:39 2023       
+---------------------------------------------------------------------------------------+
| NVIDIA-SMI 535.104.05             Driver Version: 535.104.05   CUDA Version: 12.2     |
|-----------------------------------------+----------------------+----------------------+
| GPU  Name                 Persistence-M | Bus-Id        Disp.A | Volatile Uncorr. ECC |
| Fan  Temp   Perf          Pwr:Usage/Cap |         Memory-Usage | GPU-Util  Compute M. |
|                                         |                      |               MIG M. |
|=========================================+======================+======================|
|   0  Tesla T4                       Off | 00000000:00:04.0 Off |                    0 |
| N/A   44C    P8              10W /  70W |      0MiB / 15360MiB |      0%      Default |
|                                         |                      |                  N/A |
+-----------------------------------------+----------------------+--

In [2]:
import torch
torch.cuda.is_available()

True

In [3]:
#Setup device agnostic code
device = "cuda" if torch.cuda.is_available() else "cpu"
device

'cuda'

In [4]:
#Count number of devices
torch.cuda.device_count()

1

## 3. Putting tensors (and model) on the GPUs
The reason we want our tensors/model on the GPU is because using a GPU resulst in farster computations

In [8]:
#Create a tensor (default on the CPU)
tensor = torch.tensor([1, 2, 3], device ="cpu")

#tensor not on GPU
print(tensor, tensor.device)

tensor([1, 2, 3]) cpu


In [9]:
#Move tensor to GPU(if availble)
tensor_on_gpu = tensor.to(device)
tensor_on_gpu

tensor([1, 2, 3], device='cuda:0')

In [10]:
### 4.Moving tensors back to CPU
#If tensor is on GPU, can't transform it to Numpy
tensor_on_gpu.numpy()

TypeError: ignored

In [12]:
#To fix the GPU tensor with NumPy issue, we can first set it to the CPU
tensor_back_on_cpu = tensor_on_gpu.cpu().numpy()
tensor_back_on_cpu

array([1, 2, 3])

In [ ]:
##Execises - Extra cucrriculum

Link: https://www.learnpytorch.io/00_pytorch_fundamentals/#exercises